In [63]:
import numpy as np

1- Create a numpy array of shape (3, 4) and assign random integers between 1 and 10 to every element.

In [64]:
array1 = np.random.randint(1,10,(3,4))
print(array1)

[[6 3 4 4]
 [5 5 7 9]
 [1 2 7 1]]


2- Find the maximum value in the array created in step 1.

In [65]:
array2 =array1.copy()
array_max = array2.max()
print(array_max)

9


3- Calculate the mean value of each row in the array.

In [66]:
array3 = array1.copy()
array_mean = array3.mean(axis=1)
print(array_mean)

[4.25 6.5  2.75]


4- Reshape the array from step 1 into a shape of (2, 6).

In [67]:
array4 = array1.copy()
array_reshape = array4.reshape(2,6)
print(array_reshape)

[[6 3 4 4 5 5]
 [7 9 1 2 7 1]]


5- Multiply each element in the array by 2.

In [68]:
array5 = array1.copy()
array_mul = array5*2
print(array_mul)

[[12  6  8  8]
 [10 10 14 18]
 [ 2  4 14  2]]


6- Create a numpy array with values ranging from 0 to 9. Extract the odd numbers from the array.

In [69]:
array6 = np.arange(10)
odd_number = array6[array6 % 3 == 0]
print(odd_number)


[0 3 6 9]


7- Create a 3x3 identity matrix using numpy.

In [70]:
array7 = np.identity(3)
print(array7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8- Create a 5x5 array with random values and normalize it (subtract the mean and divide by the standard deviation of the array).


In [71]:
array8 = np.random.rand(5,5)
mean = np.mean(array8)
std = np.std(array8)
normalize_array = (array8-mean)/std
print(normalize_array)

[[-1.63680184  0.17546147  1.21230711  0.29721096  0.25058878]
 [ 1.15282999 -0.82371885 -0.83346366 -0.93359354  1.10058386]
 [-1.11040565 -1.65781486 -1.2209569   0.01483571  0.87375484]
 [-0.37622912  0.13040462  1.15206125  0.21008873  0.14039181]
 [-0.59609659 -1.36494231  1.78674868  1.5635464   0.49320912]]


9- Perform element-wise multiplication between two arrays of the same shape.

In [72]:
array1
array5
array_multiply = array1 * array5
print(array_multiply)

[[36  9 16 16]
 [25 25 49 81]
 [ 1  4 49  1]]


10 - Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).


In [73]:
heights_cm = np.array([160, 170, 180, 190])
heights_inch = heights_cm / 2.54
print(np.round(heights_inch,2))

[62.99 66.93 70.87 74.8 ]


11 - Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1.


In [74]:
array_1D = np.arange(10)
array_1D
array_1D[array_1D % 2 != 0 ] = -1
print(array_1D)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


12 - Create a 2D array with random values and find the indices of the maximum and minimum values.

In [75]:
array_2D = np.random.randn(3,4)
print(array_2D)
#array_2D.ndim
#array_2D.dtype
array_2D_max = np.unravel_index(np.argmax(array_2D),array_2D.shape)
array_2D_min = np.unravel_index(np.argmin(array_2D),array_2D.shape)
print(array_2D_max)
print(array_2D_min)

[[ 0.31846396  0.55080875 -1.49474824 -1.12558987]
 [ 0.52027993 -1.00055054 -0.81995528 -0.01954176]
 [ 0.16088135  1.73574666  1.35508861 -2.01079385]]
(2, 1)
(2, 3)
